version: '3.5'
services:
  service-club:
    image: jinhong0719/dms-sms-service-club:${VERSION}.RELEASE
    container_name: service-club
    networks:
      - dms-sms-local
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - CONSUL_ADDRESS=${CONSUL_ADDRESS}
      - JAEGER_ADDRESS=${JAEGER_ADDRESS}
      - SMS_AWS_ID=${SMS_AWS_ID}
      - SMS_AWS_KEY=${SMS_AWS_KEY}
      - SMS_AWS_REGION=${SMS_AWS_REGION}
      - SMS_AWS_BUCKET=${SMS_AWS_BUCKET}
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=service-club]

networks:
  dms-sms-local:
    name: dms-sms-local
    driver: overlay
